### ISSUE TITLE
Report correct hostname in CSW responses

### ISSUE THREAD

**Issue by mpejcoch** [metno/S-ENDA-Prototype#12]
Currently pyCSW lists http://localhost:8000 (http://senda1.lab-a.met.no:8000), which makes the response readable in a browser or with curl, but won't work with QGIS.

**Comment by mpejcoch** [comment]
@epifanio  do you know how to configure pyCSW to list the correct machine name?

**Comment by mpejcoch** [comment]
Looks like it's the [server]/url parameter we're after (https://docs.pycsw.org/en/2.4.2/configuration.html), now I'm wondering if it's possible to set it dynamically.

**Comment by epifanio** [comment]
it could be possible to write a config file template and fill it with values (from docker compose environment) before to start the service.

The config is used mainly 3 times:
- [initialize the db](https://github.com/metno/S-ENDA-Prototype/blob/mmd2isofix/Volumes/CSW/commands/pycsw_setup.sh#L10)  
- [load records](https://github.com/metno/S-ENDA-Prototype/blob/mmd2isofix/Volumes/CSW/commands/pycsw_setup.sh#L11)
- [start/run the service](https://github.com/metno/S-ENDA-Prototype/blob/mmd2isofix/Volumes/CSW/commands/pycsw_setup.sh#L14) - [pycsw source](https://github.com/geopython/pycsw/blob/master/docker/entrypoint.py#L172)

the first 2 points should not use the server url, only the start service.

**Comment by mpejcoch** [comment]
> it could be possible to write a config file template and fill it with values (from docker compose environment) before to start the service.
> 
> The config is used mainly 3 times:
> 
> * [initialize the db](https://github.com/metno/S-ENDA-Prototype/blob/mmd2isofix/Volumes/CSW/commands/pycsw_setup.sh#L10)
> * [load records](https://github.com/metno/S-ENDA-Prototype/blob/mmd2isofix/Volumes/CSW/commands/pycsw_setup.sh#L11)
> * [start/run the service](https://github.com/metno/S-ENDA-Prototype/blob/mmd2isofix/Volumes/CSW/commands/pycsw_setup.sh#L14) - [pycsw source](https://github.com/geopython/pycsw/blob/master/docker/entrypoint.py#L172)
> 
> the first 2 points should not use the server url, only the start service.

OK. I was also thinking templates could work.

**Comment by mortenwh** [comment]
@epifanio - what is the status here?

**Comment by mortenwh** [comment]
This should now be solved in https://github.com/metno/S-ENDA-csw-catalog-service
