### ISSUE TITLE
Better user experince when using the development environment

### ISSUE THREAD

**Issue by aheimsbakk** [metno/S-ENDA-Prototype#21]

**Comment by aheimsbakk** [comment]
Updated development environment to only use `vagrant up` for starting and updating dockers.

Added documentation in `README.md`.

**Comment by mortenwh** [comment]
Is this done?

**Comment by aheimsbakk** [comment]
Maybe we should create an action to update it? It doesn't conform 1:1 with the current Vagrantfile in the prototype. But still works as an example.

**Comment by mortenwh** [comment]
I'm not sure what you mean by "it"..? Can you explain?
