### ISSUE TITLE
Check various testing frameworks

### ISSUE THREAD

**Issue by mortenwh** [metno/S-ENDA-Prototype#32]
Get overview of possible solutions, check them, and decide what to go. Possible solutions:

- [x] GitHub actions

- [x] Travis CI

- [x] Coveralls

- [ ] ...

**Comment by mortenwh** [comment]
What is the status here? Should it rather be done during the sprint?

**Comment by mortenwh** [comment]
I changed the milestone...

**Comment by aheimsbakk** [comment]
@mpejcoch , could we remove blocker?

I don't think this should be a blocker for "Integrate container software with CI for containers". Both actions can be done independent and merged in the end.

**Comment by mortenwh** [comment]
I thought this should be prioritized during the sprint as well.. @aheimsbakk @mpejcoch ?
