### ISSUE TITLE
Integrate software repositories with CI for unit testing 

### ISSUE THREAD

**Issue by mortenwh** [metno/S-ENDA-Prototype#33]

**Comment by aheimsbakk** [comment]
Added skeleton for unit testing in branch issue_33_unit_test, https://github.com/metno/S-ENDA-Prototype/tree/issue_33_unit_test.

**Comment by mortenwh** [comment]
Can this be considered done?

**Comment by mortenwh** [comment]
@aheimsbakk - please reopen if you disagree...
