### ISSUE TITLE
Reduce size of pyCSW docker image

### ISSUE THREAD

**Issue by mpejcoch** [metno/S-ENDA-Prototype#37]
< 100M would be nice

**Comment by mortenwh** [comment]
I move this to in progress pipeline... Is that correct? @epifanio @aheimsbakk

**Comment by aheimsbakk** [comment]
Thanks! Yes, it's correct. Repository for the container:

https://github.com/metno/pycsw-container/blob/master/Dockerfile

**Comment by aheimsbakk** [comment]
Size reduced. 

https://hub.docker.com/r/metno/pycsw

79MB

**Comment by mpejcoch** [comment]
Well done!

**Comment by mortenwh** [comment]
This is done, right? I'll close it. @mpejcoch @epifanio @aheimsbakk - please reopen if I'm wrong..
