### ISSUE TITLE
Re-factor prototype into selfcontained components

### ISSUE THREAD

**Issue by aheimsbakk** [metno/S-ENDA-Prototype#40]
To be able to work separately with one and one component we re-factor the prototype into multiple git repositories.

Stability of the end product is maintained with strong dependencies between each component version. We are using semantic versioning without the leading "v", since this is most common for docker versioning. Version of dockers should correspond to git tags.

Proposed new structure. Each component is a git repository. Propose to prefix all senda specific components with senda-.

* S-ENDA-prototype (main repository which connects everything together)
    * senda-catalog-service (uses container met-pycsw, can in the future sew together met-pysw and plugins)
        * met-pycsw (our own container based on python (alpine if possible) docker and pip package pycsw)
        * met-pycsw-plugins (repository with plugins)
    * senda-dynamic-geoassets (todays dynamic-geoassets-api)
    * senda-dashboard (todays data-dashboard)

Future re-factoring will be needed, since S-ENDA-prototype now only contains "Senda find"

**Comment by aheimsbakk** [comment]
If this this is OK? Tasks we need to do:

* [ ] Merge all outstanding pull-requests. 
* [ ] Freeze repo to a specific date.
* Create repositories
    * [ ] senda-catalog-service
    * [ ] senda-dynamic-geoassets
    * [ ] senda-dashboard
* [ ] Move code.
* [ ] Update S-ENDA-prototype repository with development environment which fetches all other repositories and starts senda proto type.

**Comment by mpejcoch** [comment]
After merging #27 we'll need one more repo for the events.

**Comment by mortenwh** [comment]
Looks good. Added events to the todo-list

**Comment by aheimsbakk** [comment]
Bump. Waiting for merge of pull request #27.

**Comment by mpejcoch** [comment]
Vi jobber med saken.

**Comment by aheimsbakk** [comment]
Thanks! :)

**Comment by aheimsbakk** [comment]
I think we're more or less done with this task.
