### ISSUE TITLE
Set up autodeployment of S-ENDA-metadata

### ISSUE THREAD

**Issue by mpejcoch** [metno/S-ENDA-Prototype#44]
Make sure that after a commit to S-ENDA-metadata the metadata get ingested by catalog-service-api and deployed to the senda1.lab-a machine

**Comment by mpejcoch** [comment]
@aheimsbakk Unfortunately the webhook 2.5.0 (which is installed in Ubuntu) does not support templates, so it's not possible to read out the secret from an external file.

**Comment by mortenwh** [comment]
This is done, isn't it?

**Comment by mpejcoch** [comment]
Yes
