### ISSUE TITLE
Why is PostGIS needed for running PyCSW?

### ISSUE THREAD

**Issue by havardf** [metno/S-ENDA-Prototype#6]

**Comment by epifanio** [comment]
PyCSW uses an SQL databse as the backend to store and idex the metadata.
There are two options:

- PostgreSQL with PostGIS spatial extension 
- Sqolite3

The choice between postgres and sqlite can be easly changed in the [pycsw configuration file](https://github.com/metno/S-ENDA-Prototype/blob/master/Volumes/CSW/conf/pycsw.cfg#L80-L84)
